name: Build

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - name: install
      run: |
        curl https://pyenv.run | bash
        export PATH="/home/runner/.pyenv/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        pip install setuptools wheel 
        pip install tox tox-pyenv pylint
        pip install .
    - name: test
      run: python -m pylint fab_oidc2